#+TITLE: Dot files
My [[https://nixos.org/][NixOS]], [[https://www.gnu.org/software/emacs/][Emacs]], and [[https://xmonad.org/][XMonad]] dot files.

Feel free to copy snippets, or use the config in its entirety.

* Installation
Assuming you have cloned the repo and ~$PWD~ is the repo, you can go
through these steps. keep in mind that these steps assume you have the
nix flakes feature enabled, so if you are on a system where you don't
have the feature yet, you can simply run these commands in
#+begin_src bash
nix-shell -p nixFlakes
#+end_src
** NixOS
This repository is a [[https://nixos.wiki/wiki/Flakes][flake]], meaning that among all the cool features,
you don't have to copy the config to =/etc/nixos/=. Running the
following should be enough to get your NixOS system up and running.
#+begin_src bash
sudo make somewhere
#+end_src
** Home-manager
To use home-manager, where most of the desktop apps reside, use
#+begin_src bash
make home-manager
#+end_src
** Emacs
Symlink the =emacs= directory to your home.
#+begin_src bash
ln -s ./emacs ~/.emacs.d
#+end_src
** XMonad
Symlink the =XMonad= directory to your home.
#+begin_src bash
ln -s ./xmonad ~/.xmonad
#+end_src

** Nyxt
Symlink the =Nyxt= directory to your home.
#+begin_src bash
ln -s ./nyxt ~/.config/nyxt
#+end_src
