# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/8ef07316-37bf-46d0-890a-000faf3bf788";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."nixenv".device = "/dev/disk/by-uuid/2ae649d5-59d9-485b-ac89-75aab6fd1a90";

  swapDevices =
    [ { device = "/dev/disk/by-uuid/60da3e35-4607-4c70-9564-baf99dd15bfe"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
