# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [
      # <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/da1d44dd-5bf1-443e-b4e5-d3ae768aeb75";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."nixenc".device = "/dev/disk/by-uuid/5a77cb61-75cb-47d0-ba32-c5f34d7232ce";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5D27-B276";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/9ca8907f-5908-4bdc-83a2-54faa4f0dee9"; }
    ];

  nix.maxJobs = lib.mkDefault 8;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
